apiVersion: v1
kind: ServiceAccount
metadata:
  name: nvidia-node-tagger
  namespace: cluster-addons-nvidia-node-tagger
automountServiceAccountToken: true

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-manager
  namespace: cluster-addons-nvidia-node-tagger
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-manager@nvidia-node-tagger
  namespace: cluster-addons-nvidia-node-tagger
roleRef:
  kind: Role
  name: pod-manager
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: nvidia-node-tagger
    namespace: cluster-addons-nvidia-node-tagger

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-manager
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-manager@nvidia-node-tagger
subjects:
- kind: ServiceAccount
  name: nvidia-node-tagger
  namespace: cluster-addons-nvidia-node-tagger
roleRef:
  kind: ClusterRole
  name: node-manager
  apiGroup: rbac.authorization.k8s.io
